name: Build and test feature branch
on:
  push:
    branches:
      - feature/*
jobs:
  build-feature:
    runs-on: ubuntu-latest
    steps:
      - name: TEST Actions local
        run: echo El workflow se ha ejecutado
      
      ###########################################
      # 1- Download source code from branch that triggered theworkflow, setup java and check that source code is buildable
      ###########################################
      - name: Checkout from branch that triggered
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha}}